# Generated migration - Consolidated for Supabase PostgreSQL
# Removed TimescaleDB-specific code and time fields

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crystals_app', '0001_baseline_existing_schema'),
    ]

    operations = [
        # ===============================================================
        # CREAR TODOS LOS MODELOS (SIN TIME FIELDS)
        # ===============================================================
        
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=50)),
                ('validated', models.IntegerField()),
            ],
            options={
                'db_table': 'activation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrixCalculatorData',
            fields=[
                ('tc', models.FloatField(primary_key=True, serialize=False)),
                ('pureza', models.FloatField()),
                ('ss', models.FloatField()),
                ('brx', models.FloatField()),
            ],
            options={
                'db_table': 'brix_calculator_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('pixels_per_metric', models.FloatField()),
                ('metric_name', models.CharField(max_length=5)),
                ('range', models.CharField(max_length=50)),
                ('active', models.IntegerField(default=0)),
                ('powder', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'calibrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('logo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=3, unique=True)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrudoCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti', models.IntegerField(blank=True, null=True)),
                ('ft3_per_templa', models.IntegerField(blank=True, null=True)),
                ('bx_masa_c', models.IntegerField(blank=True, db_column='bx_masa__c', null=True)),
                ('no_templas', models.IntegerField(blank=True, null=True)),
                ('porcentaje_cristales', models.IntegerField(blank=True, null=True)),
                ('tamano_final_polv', models.IntegerField(blank=True, null=True)),
                ('concentracion_slurry', models.IntegerField(blank=True, null=True)),
                ('alcohol_slurry', models.IntegerField(blank=True, null=True)),
                ('densidad_slurry', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crudo_calculations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrystalsDataParametrization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'crystals_data_parametrization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrystalsDataParametrizationCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('tolerance', models.IntegerField(blank=True, null=True)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'crystals_data_parametrization_cv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrystalsDataParametrizationMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('tolerance', models.IntegerField(blank=True, null=True)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'crystals_data_parametrization_ma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrystalsDataParametrizationNewParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'crystals_data_parametrization_nw_params',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneralReportingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=25, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'general_reporting_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'global_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LabMaterialsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('visible', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lab_materials_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryCalculatedMasaAParametrization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'laboratory_calculated_masa_a_parametrization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryCalculatedMasaBParametrization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'laboratory_calculated_masa_b_parametrization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryCalculatedMasaCParametrization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'laboratory_calculated_masa_c_parametrization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryCalculatedRefinoParametrization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'laboratory_calculated_refino_parametrization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.CharField(blank=True, max_length=50, null=True)),
                ('pza_licor', models.IntegerField(blank=True, null=True)),
                ('pza_sirope', models.IntegerField(blank=True, null=True)),
                ('pza_masa_refino', models.IntegerField(blank=True, null=True)),
                ('pza_magma_b', models.IntegerField(blank=True, null=True)),
                ('pza_meladura', models.IntegerField(blank=True, null=True)),
                ('pza_masa_a', models.IntegerField(blank=True, null=True)),
                ('pza_lavado_a', models.IntegerField(blank=True, null=True)),
                ('pza_nutsch_a', models.IntegerField(blank=True, null=True)),
                ('pza_magma_c', models.IntegerField(blank=True, null=True)),
                ('pza_miel_a', models.IntegerField(blank=True, null=True)),
                ('pza_masa_b', models.IntegerField(blank=True, null=True)),
                ('pza_nutsch_b', models.IntegerField(blank=True, null=True)),
                ('pza_cr_des', models.IntegerField(blank=True, null=True)),
                ('pza_miel_b', models.IntegerField(blank=True, null=True)),
                ('pza_masa_c', models.IntegerField(blank=True, null=True)),
                ('pza_nutsch_c', models.IntegerField(blank=True, null=True)),
                ('pza_miel_final', models.IntegerField(blank=True, null=True)),
                ('bx_masa_c', models.IntegerField(blank=True, null=True)),
                ('bx_cristal_des', models.IntegerField(blank=True, null=True)),
                ('bx_nutsch_c', models.IntegerField(blank=True, null=True)),
                ('bx_masa_b', models.IntegerField(blank=True, null=True)),
                ('bx_masa_a', models.IntegerField(blank=True, null=True)),
                ('bx_magma_b', models.IntegerField(blank=True, null=True)),
                ('bx_masa_refino', models.IntegerField(blank=True, null=True)),
                ('bx_magma_c', models.IntegerField(blank=True, null=True)),
                ('bx_miel_final', models.IntegerField(blank=True, null=True)),
                ('bx_nutsch_b', models.IntegerField(blank=True, null=True)),
                ('bx_miel_b', models.IntegerField(blank=True, null=True)),
                ('bx_miel_a', models.IntegerField(blank=True, null=True)),
                ('bx_lavado_a', models.IntegerField(blank=True, null=True)),
                ('bx_nutsch_a', models.IntegerField(blank=True, null=True)),
                ('bx_sirope', models.IntegerField(blank=True, null=True)),
                ('bx_del_licor', models.IntegerField(blank=True, null=True)),
                ('bx_meladura', models.IntegerField(blank=True, null=True)),
                ('pol_azuc', models.IntegerField(blank=True, null=True)),
                ('sol_tota_hda_azu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryParametrization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'laboratory_parametrization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratoryReportingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=25, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_reporting_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratorySettingsExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pza_licor_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_licor_number', models.IntegerField(blank=True, null=True)),
                ('pza_sirope_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_sirope_number', models.IntegerField(blank=True, null=True)),
                ('pza_masa_refino_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_masa_refino_number', models.IntegerField(blank=True, null=True)),
                ('pza_magma_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_magma_b_number', models.IntegerField(blank=True, null=True)),
                ('pza_meladura_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_meladura_number', models.IntegerField(blank=True, null=True)),
                ('pza_masa_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_masa_a_number', models.IntegerField(blank=True, null=True)),
                ('pza_lavado_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_lavado_a_number', models.IntegerField(blank=True, null=True)),
                ('pza_nutsch_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_nutsch_a_number', models.IntegerField(blank=True, null=True)),
                ('pza_magma_c_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_magma_c_number', models.IntegerField(blank=True, null=True)),
                ('pza_miel_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_miel_a_number', models.IntegerField(blank=True, null=True)),
                ('pza_masa_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_masa_b_number', models.IntegerField(blank=True, null=True)),
                ('pza_nutsch_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_nutsch_b_number', models.IntegerField(blank=True, null=True)),
                ('pza_cr_des_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_cr_des_number', models.IntegerField(blank=True, null=True)),
                ('pza_miel_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_miel_b_number', models.IntegerField(blank=True, null=True)),
                ('pza_masa_c_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_masa_c_number', models.IntegerField(blank=True, null=True)),
                ('pza_nutsch_c_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_nutsch_c_number', models.IntegerField(blank=True, null=True)),
                ('pza_miel_final_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pza_miel_final_number', models.IntegerField(blank=True, null=True)),
                ('bx_masa_c_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_masa_c_number', models.IntegerField(blank=True, null=True)),
                ('bx_cristal_des_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_cristal_des_number', models.IntegerField(blank=True, null=True)),
                ('bx_nutsch_c_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_nutsch_c_number', models.IntegerField(blank=True, null=True)),
                ('bx_masa_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_masa_b_number', models.IntegerField(blank=True, null=True)),
                ('bx_masa_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_masa_a_number', models.IntegerField(blank=True, null=True)),
                ('bx_magma_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_magma_b_number', models.IntegerField(blank=True, null=True)),
                ('bx_masa_refino_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_masa_refino_number', models.IntegerField(blank=True, null=True)),
                ('bx_magma_c_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_magma_c_number', models.IntegerField(blank=True, null=True)),
                ('bx_miel_final_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_miel_final_number', models.IntegerField(blank=True, null=True)),
                ('bx_nutsch_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_nutsch_b_number', models.IntegerField(blank=True, null=True)),
                ('bx_miel_b_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_miel_b_number', models.IntegerField(blank=True, null=True)),
                ('bx_miel_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_miel_a_number', models.IntegerField(blank=True, null=True)),
                ('bx_lavado_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_lavado_a_number', models.IntegerField(blank=True, null=True)),
                ('bx_nutsch_a_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_nutsch_a_number', models.IntegerField(blank=True, null=True)),
                ('bx_sirope_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_sirope_number', models.IntegerField(blank=True, null=True)),
                ('bx_del_licor_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_del_licor_number', models.IntegerField(blank=True, null=True)),
                ('bx_meladura_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('bx_meladura_number', models.IntegerField(blank=True, null=True)),
                ('pol_azuc_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('pol_azuc_number', models.IntegerField(blank=True, null=True)),
                ('sol_tota_hda_azu_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('sol_tota_hda_azu_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_settings_excel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManagementReportLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('element_id', models.TextField()),
                ('element_type', models.TextField()),
            ],
            options={
                'db_table': 'management_report_layout',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManagementReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_variable', models.IntegerField()),
                ('cv_variable', models.IntegerField()),
                ('perc_fino', models.IntegerField()),
                ('perc_peq', models.IntegerField()),
                ('perc_opt', models.IntegerField()),
                ('perc_gran', models.IntegerField()),
                ('perc_muygran', models.IntegerField()),
                ('rel_la', models.IntegerField()),
                ('perc_crst_alarg', models.IntegerField()),
                ('pza_licor', models.IntegerField()),
                ('pza_sirope', models.IntegerField()),
                ('pza_masa_refino', models.IntegerField()),
                ('pza_magma_b', models.IntegerField()),
                ('pza_meladura', models.IntegerField()),
                ('pza_masa_a', models.IntegerField()),
                ('pza_lavado_a', models.IntegerField()),
                ('pza_nutsch_a', models.IntegerField()),
                ('pza_magma_c', models.IntegerField()),
                ('pza_miel_a', models.IntegerField()),
                ('pza_masa_b', models.IntegerField()),
                ('pza_nutsch_b', models.IntegerField()),
                ('pza_cr_des', models.IntegerField()),
                ('pza_miel_b', models.IntegerField()),
                ('pza_masa_c', models.IntegerField()),
                ('pza_nutsch_c', models.IntegerField()),
                ('pza_miel_final', models.IntegerField()),
                ('bx_masa_c', models.IntegerField()),
                ('bx_cristal_des', models.IntegerField()),
                ('bx_nutsch_c', models.IntegerField()),
                ('bx_masa_b', models.IntegerField()),
                ('bx_masa_a', models.IntegerField()),
                ('bx_magma_b', models.IntegerField()),
                ('bx_masa_refino', models.IntegerField()),
                ('bx_magma_c', models.IntegerField()),
                ('bx_miel_final', models.IntegerField()),
                ('bx_nutsch_b', models.IntegerField()),
                ('bx_miel_b', models.IntegerField()),
                ('bx_miel_a', models.IntegerField()),
                ('bx_lavado_a', models.IntegerField()),
                ('bx_nutsch_a', models.IntegerField()),
                ('bx_sirope', models.IntegerField()),
                ('bx_del_licor', models.IntegerField()),
                ('bx_meladura', models.IntegerField()),
                ('pol_azuc', models.IntegerField()),
                ('sol_tota_hda_azu', models.IntegerField()),
                ('rel_la_grapgh', models.IntegerField()),
            ],
            options={
                'db_table': 'management_report_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManualMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'manual_measurements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewParametersAnalysisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'new_parameters_analysis_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcessCodeData',
            fields=[
                ('process', models.FloatField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'process_code_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefinoCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_azucar', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.IntegerField(blank=True, null=True)),
                ('volumen_tacho', models.IntegerField(blank=True, null=True)),
                ('densidad_grano', models.IntegerField(blank=True, null=True)),
                ('rendimiento_solidos', models.IntegerField(blank=True, null=True)),
                ('concentracion_masacocida', models.IntegerField(blank=True, null=True)),
                ('am_semilla_lock', models.IntegerField(blank=True, null=True)),
                ('concentracion_slurry', models.IntegerField(blank=True, null=True)),
                ('alcohol_slurry', models.IntegerField(blank=True, null=True)),
                ('densidad_slurry', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refino_calculations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecificReportingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=25, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specific_reporting_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        
        # Modelos independientes (sin FK) - previamente candidatos a hypertables
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField(default=0.0)),
                ('cv', models.FloatField(default=0.0)),
                ('pct_fine', models.FloatField(default=0.0)),
                ('pct_small', models.FloatField(default=0.0)),
                ('pct_optimal', models.FloatField(default=0.0)),
                ('pct_large', models.FloatField(default=0.0)),
                ('pct_very_large', models.FloatField(default=0.0)),
                ('ratio_l_to_w', models.FloatField(default=0.0)),
                ('elongated_crystals', models.FloatField(default=0.0)),
                ('pct_powder', models.FloatField(default=0.0)),
                ('historic_report_id', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'analysis_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'numero',
                'managed': True,
            },
        ),
        
        # Modelos con ForeignKey (no se pueden convertir a hypertables en TimescaleDB)
        migrations.CreateModel(
            name='HistoricReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=50)),
                ('calibration', models.CharField(max_length=20)),
                ('correlation', models.FloatField()),
                ('width_min', models.FloatField()),
                ('width_max', models.FloatField()),
                ('width_sd', models.FloatField()),
                ('width_cv', models.FloatField()),
                ('width_mean', models.FloatField()),
                ('width_sum', models.FloatField()),
                ('width_samples', models.FloatField()),
                ('width_range', models.FloatField()),
                ('height_min', models.FloatField()),
                ('height_max', models.FloatField()),
                ('height_sd', models.FloatField()),
                ('height_cv', models.FloatField()),
                ('height_mean', models.FloatField()),
                ('height_sum', models.FloatField()),
                ('height_samples', models.FloatField()),
                ('height_range', models.FloatField()),
                ('calibration_fk', models.ForeignKey(db_column='calibration_id', on_delete=django.db.models.deletion.CASCADE, to='crystals_app.calibration')),
            ],
            options={
                'db_table': 'historic_reports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_class', models.CharField(max_length=20)),
                ('object_length', models.FloatField()),
                ('pct_object_length', models.FloatField()),
                ('mean_object_length', models.FloatField()),
                ('object_width', models.FloatField()),
                ('pct_object_width', models.FloatField()),
                ('mean_object_width', models.FloatField()),
                ('long_crystals', models.FloatField(blank=True, null=True)),
                ('historic_report', models.ForeignKey(db_column='historic_reports_id', on_delete=django.db.models.deletion.CASCADE, to='crystals_app.historicreport')),
            ],
            options={
                'db_table': 'historic_analysis_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnalysisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('baking_time', models.IntegerField(blank=True, null=True)),
                ('mass_number', models.IntegerField(blank=True, null=True)),
                ('historic_report', models.ForeignKey(db_column='historic_reports_id', on_delete=django.db.models.deletion.CASCADE, to='crystals_app.historicreport')),
            ],
            options={
                'db_table': 'analysis_categories',
                'managed': True,
            },
        ),
    ]
