# Generated by Django 4.2.24 on 2025-10-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0003_setup_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='target_cv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='target_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='amount_perc_fino',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='amount_perc_gran',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='amount_perc_muy_gran',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='amount_perc_opt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='amount_perc_peq',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='amount_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='managementreportsettings',
            name='perc_powder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
