# Generated by Django 4.2.24 on 2025-10-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0004_calibration_ordering_calibration_target_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processcodedata',
            name='process',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
