# Generated by Django 4.2.24 on 2025-10-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0005_alter_config_key_alter_config_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
