# Generated by Django 4.2.24 on 2025-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0006_increase_calibration_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicreport',
            name='calibration',
            field=models.CharField(max_length=50),
        ),
    ]
