# Generated by Django 4.2.24 on 2025-12-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0008_activation_factory_id_analysiscategory_factory_id_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='factory_id',
        #     field=models.IntegerField(default=1),
        # ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_cristal_des_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_del_licor_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_lavado_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_magma_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_magma_c_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_c_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_refino_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_meladura_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_miel_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_miel_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_miel_final_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_nutsch_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_nutsch_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_nutsch_c_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_sirope_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pol_azuc_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_cr_des_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_lavado_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_licor_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_magma_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_magma_c_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_c_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_refino_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_meladura_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_miel_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_miel_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_miel_final_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_nutsch_a_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_nutsch_b_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_nutsch_c_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_sirope_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='sol_tota_hda_azu_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
