# Generated by Django 4.2.24 on 2025-12-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0009_user_factory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='factory_id',
            field=models.IntegerField(default=1),
        ),
    ]
