# Generated by Django 4.2.24 on 2025-12-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0010_user_factory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_cristal_des_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_del_licor_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_lavado_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_magma_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_magma_c_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_c_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_masa_refino_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_meladura_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_miel_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_miel_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_miel_final_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_nutsch_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_nutsch_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_nutsch_c_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='bx_sirope_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pol_azuc_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_cr_des_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_lavado_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_licor_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_magma_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_magma_c_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_c_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_masa_refino_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_meladura_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_miel_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_miel_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_miel_final_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_nutsch_a_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_nutsch_b_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_nutsch_c_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='pza_sirope_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorysettingsexcel',
            name='sol_tota_hda_azu_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
