# Generated by Django 4.2.24 on 2025-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0011_alter_laboratorysettingsexcel_bx_cristal_des_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manualmeasurement',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
