# Generated by Django 4.2.24 on 2025-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0012_alter_company_logo_alter_manualmeasurement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_cristal_des',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_del_licor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_lavado_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_magma_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_magma_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_masa_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_masa_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_masa_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_masa_refino',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_meladura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_miel_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_miel_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_miel_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_nutsch_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_nutsch_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_nutsch_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='bx_sirope',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pol_azuc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_cr_des',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_lavado_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_licor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_magma_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_magma_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_masa_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_masa_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_masa_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_masa_refino',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_meladura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_miel_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_miel_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_miel_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_nutsch_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_nutsch_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_nutsch_c',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='pza_sirope',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorydata',
            name='sol_tota_hda_azu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
