# Generated by Django 4.2.24 on 2026-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0018_heritage_blockedip_analysisresults_factory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_id', models.IntegerField(default=1)),
                ('fecha_hora', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_error', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('contexto', models.CharField(blank=True, max_length=255, null=True)),
                ('modo', models.CharField(blank=True, max_length=10, null=True)),
                ('version_app', models.CharField(blank=True, max_length=20, null=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'error_log',
                'managed': True,
            },
        ),
    ]
