# Generated by Django 4.2.24 on 2026-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystals_app', '0020_enable_aditional_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='aditional_ranges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='category_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
